## 端⼝号 上下⽂路径
server:
  port: 8080
  servlet:
    context-path: /crm
spring:
  ## 数据源配置
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/crm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: bjmsb
  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
  ## 启⽤热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      #exclude: WEB-INF/**

# mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.lyf.crm24.vo;com.lyf.crm24.query;com.lyf.crm24.dto
  configuration:
    map-underscore-to-camel-case: true
# pageHelper 分⻚
pagehelper:
  helper-dialect: mysql

## 设置 dao ⽇志打印级别
logging:
  level:
    com:
      lyf:
        crm24:
          dao: debug
